name: go_smart
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

# == Dont use any package here this not good for me, Thanks ==  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.1.0
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.6.0
  readmore: ^2.2.0
  # State managment here
  get: ^4.6.6
  intl: ^0.19.0
  flutter_svg: ^2.0.9
  dropdown_button2: ^2.3.9
  iconsax: ^0.0.8
  image_picker: ^1.0.7
  geolocator: ^10.1.1
  url_launcher: ^6.2.4
  permission_handler: ^11.2.1
  geocoding: ^2.1.1
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  webview_flutter: ^4.8.0



dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/hotels/
    - assets/images/foods/
    - assets/images/cities/
    - assets/images/landmarks/
    - assets/images/activities/
    - assets/images/activities/details/
    - assets/images/tourguides/
    - assets/images/gallery/
    - assets/images/summer_offers/
    - assets/images/weekend_offers/
    - assets/icons/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Urbanist 
      fonts:
        - asset: assets/fonts/urbanist/Urbanist-Bold.ttf
        - asset: assets/fonts/urbanist/Urbanist-Italic.ttf
        - asset: assets/fonts/urbanist/Urbanist-Medium.ttf
        - asset: assets/fonts/urbanist/Urbanist-Regular.ttf
        - asset: assets/fonts/urbanist/Urbanist-SemiBold.ttf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

